specfile_path: ansible-bender.spec
actions:
  create-archive:
    - "python3 -m build"
    - "sh -c 'ls -1 dist/ansible-bender-$(python3 -m setuptools_scm).tar.gz'"
  get-current-version:
    - "python3 -m setuptools_scm"
jobs:
- job: copr_build
  targets:
  - fedora-rawhide
  # fedora 36 has old setuptools
  - fedora-37
  trigger: pull_request
- job: tests
  trigger: pull_request
  targets:
  - fedora-rawhide
  - fedora-37
srpm_build_deps:
  - python3-build
  - python3-setuptools
  - python3-setuptools_scm
