specfile_path: ansible-bender.spec
actions:
  create-archive:
    - "python3 setup.py sdist --dist-dir ."
    - "sh -c 'echo ansible-bender-$(python3 setup.py --version).tar.gz'"
  get-current-version:
    - "python3 setup.py --version"
jobs:
- job: copr_build
  targets:
  - fedora-all
  trigger: pull_request
- job: tests
  trigger: pull_request
  targets:
  - fedora-all
- job: propose_downstream
  trigger: release
  dist_git_branches: [rawhide]
srpm_build_deps:
  - python3-pip # "python3 setup.py --version" needs it
  - python3-setuptools_scm
